name: 🚀 Deploy PHP para HostGator

on:
  push:
    branches:
      - vagner  # dispara quando fizer push na branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 📂 Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_path: "./"
          remote_path: "/home2/vagn5934/vagnerferreiralimaju1756074880000.0/vagner"
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/*
            **/tests/*
