name: 🚀 Deploy PHP para HostGator via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.tbfood.com.br
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./           # se seu código todo for pra raiz
          server-dir: /public_html  # ajuste se for outra pasta no HostGator
          # excluir coisas desnecessárias, se quiser:
          exclude: |
            **/.git*
            **/.github*
            node_modules/
            .env
            .env.local
